version: '3.8'
services:
  mysql:
    container_name: mysql
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_SCHEMA}
      #MYSQL_USER: ${DB_USER}
      #MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./app/db/sql/init.mysql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - '8080:8080'

  python:
    container_name: python3.10
    build:
      context: .
      dockerfile: ./Dockerfile
    image: python3.10-fastapi
    volumes:
      - ./:/code
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
    ports:
      - '8001:80'